### ISSUE TITLE
Exposed AWS Access Key ID Value

### ISSUE THREAD

**Issue by l3d00m** [leejinseok/spring-blog#3]
Potential security breach. See https://github.com/leejinseok/spring-blog/blob/master/backend/src/main/java/com/wonder/blog/util/AwsS3Util.java#L19

Found through https://shhgit.darkport.co.uk/

**Comment by photoangell** [comment]
darkport is on hackernews right now, so you may be getting a lots of hits on this issue.

**Comment by technimad** [comment]
I see a commit which removes the keys, but note that they are still visible in older commits. So revoke the keys and better, rewrite your git history to filter out the credentials completely.

https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository
